### ISSUE TITLE
Error when I try to put a background

### ISSUE THREAD

**Issue by t-benedet** [hugo-toha/hugo-toha.github.io#103]
Hi,

First of all, thanks for this good theme for hugo ! Great work !

I've a problem when I try to put a background. I've a `background.jpg` picture in my `/resources/_gen/images` directory.

Here is the params section of my config.yaml file :

```
# Site parameters
params:
  background: "images/background.jpg"
  gitRepo: https://github.com/t-benedet/blog.git
  enableBlogPost: true
  enableTOC: true
  newsletter:
    enable: false
~                  
```

But on my workflow I've this error :

```
Run hugo --minify
Start building sites … 
Total in 102 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:49:8: executing "index.html" at <partial "sections/home.html" .>: error calling partial: "/home/runner/work/blog/blog/themes/toha/layouts/partials/sections/home.html:46:16": execute of template failed: template: partials/sections/home.html:46:16: executing "partials/sections/home.html" at <$src.Resize>: nil pointer evaluating resource.Resource.Resize
Error: Process completed with exit code 255.
```

My repo => https://github.com/t-benedet/blog

Can you tell me what where is my mistake ? 

Thanks a lot !

**Comment by hossainemruz** [comment]
Your images should be in `assets/images` folder instead of `resources/_gen/images`.

**Comment by t-benedet** [comment]
Hum... I dont have a assets/images folder so I created it at the root of my blog ( https://github.com/t-benedet/blog/tree/source/assets/images ) and I put my pictures on it. 

If I keep my current params sections like that : 
```
# Site parameters
params:
  background: "images/background.jpg"
  gitRepo: https://github.com/t-benedet/blog.git
  enableBlogPost: true
  enableTOC: true
  newsletter:
    enable: false
```

The workflow works but my pictures doesn't appear as a background ( still a white color as a background as you can see here : https://t-benedet.github.io/blog/ )

If I change the background variable in the params section like that : 
```
 background: "assets/images/background.jpg"
```

I've the same error as my first post. 

I think I've missed something...

**Comment by hossainemruz** [comment]
Use
```
 background: "images/background.jpg"
```
