### ISSUE TITLE
unmarshal of format "" is not supported

### ISSUE THREAD

**Issue by lbdhr** [hugo-toha/hugo-toha.github.io#202]
Hi, thank you for creating the theme. But I encounted a problem when I am initing the theme following: `https://toha-guides.netlify.app/posts/getting-started/prepare-site/`. I am using the macOS Catalina 10.15.7.   The version of hugo is: `hugo v0.104.3`

The problem showed after I added an image file in `data/en/images/author/` path. When I ran the command `hugo server -t toha -w`, I got an error called `Error: Error building site: failed to load data: failed to load data: "/Users/xxx/Desktop/xxx/xxx.github.io/data/en/images/author/tn2.png:1:1": unmarshal of format "" is not supported`.

Could you help me to solve it? Thank you.

**Comment by hossainemruz** [comment]
Hi @lbdhr. Don't put images into data directory. Put them in `assets` directory. Data directory supposed to hold only `YAML`, `JSON`, `XML`, and `TOML` files.

**Comment by lbdhr** [comment]
Thank you very much. I am new to here :)
