### ISSUE TITLE
Search page showing 'search results' posts.

### ISSUE THREAD

**Issue by hng12** [hugo-toha/hugo-toha.github.io#205]
<img width="1099" alt="Screenshot 2022-11-04 at 8 31 37 PM" src="https://user-images.githubusercontent.com/58843937/200068822-948d5792-c98f-474a-85b5-c2a59890f51c.png">

This is on the demo site. When searching for a word that is contained in the default 'search results' page, all the search result pages of all languages come up

**Comment by hossainemruz** [comment]
I can confirm the issue.

**Comment by hng12** [comment]
Just realised i put this in the wrong repo, meant to put it in the main one that hosts the theme itself, sorry!

**Comment by hossainemruz** [comment]
@hng12 It should be fixed by https://github.com/hugo-toha/toha/pull/690. Please upgrade your theme to latest commit and check if the issue still persist.
