### ISSUE TITLE
Not able to find a proper repo to use as a template.

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [hugo-toha/hugo-toha.github.io#266]
I am interested to create a portfolio website for myself so I tried cloning this [repo ](https://github.com/hugo-toha/hugo-toha.github.io) everything was fine later realized I can't customize the footer as this [repo ](https://github.com/hugo-toha/hugo-toha.github.io)doesn't have  **layouts/paritals/footer.html**.

So I cloned another repo where I was able to find **footer.html** but if I use this [repo](https://github.com/hugo-toha/toha/releases/tag/v3.8.0) I get a sample site where it only has home section other sections like education, skills are not enabled as given in the below image kindly help how to enable this section in this [repo](https://github.com/hugo-toha/toha/releases/tag/v3.8.0)

![Test](https://github.com/hugo-toha/hugo-toha.github.io/assets/16875250/6287bb07-73c7-49b8-95c5-38cda8fd776b)

FYI @hossainemruz

**Comment by hossainemruz** [comment]
What do you need to customize in footer?

**Comment by Santosh-Kumar-Perumal** [comment]
I need to remove "Stay up to date with email notification" section and remove the footer

**Comment by hossainemruz** [comment]
You can change footer configuration using `config.yaml` file. Take a look here: https://github.com/hugo-toha/hugo-toha.github.io/blob/b90ec12a0cd3aab18130e8e3c44167c2ef80445a/config.yaml#L268

**Comment by Santosh-Kumar-Perumal** [comment]
I tried removed the entire section still not able to get rid of it please see my code and site.
https://github.com/Santosh-Kumar-Perumal/my-hugo-website/blob/main/config.yaml
https://santosh-kumar-perumal.netlify.app/

**Comment by Santosh-Kumar-Perumal** [comment]
using the below repo I am able to remove the footer but not able to enable the sections can you please help.
Repo: https://github.com/hugo-toha/toha/releases/tag/v3.8.0

![image](https://github.com/hugo-toha/hugo-toha.github.io/assets/16875250/2cdd4c5e-9624-4e85-b1af-2bd0893ae3b3)

**Comment by Santosh-Kumar-Perumal** [comment]
Did a workaround by adding layouts/partial/footer.html it worked but left with one more issue which is background blur issue which has to be changed in home.css but unfortunately in my repo I don't have home.css file.

**Comment by hossainemruz** [comment]
Just put the respective CSS overwrite under `assets/styles/override.scss` file in your repo.

**Comment by Santosh-Kumar-Perumal** [comment]
Thanks @hossainemruz I don't have a **styles** folder in my repo below is the repo that I cloned.

https://github.com/hugo-toha/hugo-toha.github.io

**Comment by hossainemruz** [comment]
Just create `styles` folder under `assets` directory of your repo. Then create `override.scss` file there.

**Comment by Santosh-Kumar-Perumal** [comment]
Thanks @hossainemruz  even after adding still the backgroup image blur I am not able to disable it.

![image](https://github.com/hugo-toha/hugo-toha.github.io/assets/16875250/51da8fe9-9ce1-4090-9455-7a0c570fbf18)

**Comment by hossainemruz** [comment]
I asked you to create `override.scss` file in your `assets/styles` folder. Why did you copied all the CSS from theme in `static` directory?

>Why can't we use the below repo which has all the folders and options to edit everything? This below repo has everything, and we can customize just that it is not showing the other sections like education, skills etc.. how to fix it
https://github.com/hugo-toha/toha

It has been designed as theme to used by other site. You actually can use this repo directly but that will cause more trouble and work.

**Comment by Santosh-Kumar-Perumal** [comment]
Sure thanks will copy only override.css but the contents inside the file is commented do I need to un comment it ?

**Comment by hossainemruz** [comment]
Just create `override.sccs` file in your `assets/styles` directory and put the following css there.

```scss
.home {
  .background {
    filter: none !important;
  }
}
```

**Comment by Santosh-Kumar-Perumal** [comment]
Thanks a lot it worked like wise can I change style settings for skills section I want the size of the skills section to be reduced please suggest how to do it for skills sesction

**Comment by hossainemruz** [comment]
Yes. Just put the respective CSS in the `override.scss` file. That will overwrite css from respective `skills.scss` file.

**Comment by hossainemruz** [comment]
Please, close the issue if your problem is solved.

**Comment by Santosh-Kumar-Perumal** [comment]
Please guide me for skills it is shwoing error.
![image](https://github.com/hugo-toha/hugo-toha.github.io/assets/16875250/fd910314-81b2-460a-b369-e29fa67a392d)

**Comment by hossainemruz** [comment]
Just put this css in `ovewrite.scss`. You don't have to copy all css from `skills.scss` file.
```scss
.skills-section {
  .card{
    margin: none;
     .card-body{
       display: none;
     }
  } 
}
```

**Comment by Santosh-Kumar-Perumal** [comment]
Thanks, It reduced some of the size but I need to get rid of the space completely any idea?

Before
![image](https://github.com/hugo-toha/hugo-toha.github.io/assets/16875250/580c1e2d-cb41-4eb1-b4f3-d456027483f3)


After your suggestion
![image](https://github.com/hugo-toha/hugo-toha.github.io/assets/16875250/298748d7-66b0-40c7-9e93-37cac09b9c9c)

I am trying to do is 
![image](https://github.com/hugo-toha/hugo-toha.github.io/assets/16875250/35f41139-872d-44d0-ac13-d1fb5223a0b8)

**Comment by hossainemruz** [comment]
Change `margin: none` to `margin: 0`.
```css
.skills-section {
  .card{
    margin: 0;
    .card-body{
       display: none;
     }
  } 
}
```

**Comment by Santosh-Kumar-Perumal** [comment]
Thanks, a lot rockstar @hossainemruz closing the issue.

**Comment by Santosh-Kumar-Perumal** [comment]
@hossainemruz was really helpful and patient and suggested the fix for my issue great contributor and maintainer @hossainemruz  rockstar
