### ISSUE TITLE
Align card text to left

### ISSUE THREAD

**Issue by steffenba** [hugo-toha/hugo-toha.github.io#330]
Hey there!

Thank you for your work on this theme. 

I would like to propose a small CSS change, that would make the cards more pleasant to the eye. The "cards" currently use "justify" to align the card texts. This looks a bit odd in my opinion, and I propose that the default should be "left".

Current version:
![image](https://github.com/user-attachments/assets/6becf627-5fd8-4077-b231-92aa0b01184f)

Fixed version:
![image](https://github.com/user-attachments/assets/c6982804-12ed-4d59-8fdc-8014d1bcda41)

Thank you for your consideration!

**Comment by BernatBC** [comment]
Thank you @steffenba 
I agree that aligning the text left on narrow boxes looks better. If you want, create a Pull Request on https://github.com/hugo-toha/toha
