### ISSUE TITLE
Newsletter field is not visible on dark theme

### ISSUE THREAD

**Issue by the-whiz84** [hugo-toha/hugo-toha.github.io#348]
Hello,

I have setup Mailchimp and tested it working. On light theme, the Newsletter field looks great but on dark theme, the background of input field is black and so is the text.
It is not visible unless you highlight it.

My [website](https://zerodawn.tech)
My [Repo](https://github.com/the-whiz84/zerodawn.tech)

<img width="1693" alt="Screenshot 2024-10-20 at 11 58 13" src="https://github.com/user-attachments/assets/aa55b9a3-4ed2-4810-971a-f0f86ddcf0a2">
<img width="1693" alt="Screenshot 2024-10-20 at 11 58 49" src="https://github.com/user-attachments/assets/c739f765-814b-4280-a85f-5f10b5894cbf">
<img width="1693" alt="Screenshot 2024-10-20 at 11 58 57" src="https://github.com/user-attachments/assets/5e63799f-89b7-4cb2-a275-f4e1117fb463">

**Comment by hossainemruz** [comment]
Thank you @the-whiz84! I will take a look soon.

**Comment by joyao** [comment]
Hi @hossainemruz, I can fix this issue.

**Comment by hossainemruz** [comment]
Thank you @joyao! Please, go ahead.
