### ISSUE TITLE
How to adjust the image compression level?

### ISSUE THREAD

**Issue by h3jia** [hugo-toha/hugo-toha.github.io#349]
Hello, is there a way to adjust the compression level of e.g. the headshot photo and the background image?

I feel that by default they are compressed too much, i.e. even if I provide high resolution images they will be over-compressed and therefore look blurred. For example, you can compare my GitHub avatar and the headshot photon on [my website](https://hejia.io).

Could you help me look into this? Thanks.

**Comment by joyao** [comment]
Hi @h3jia, the images in this project may be compressed automatically. Currently, we do not provide user settings to change the resolution, but you can change the [home.html "148*148" setting](https://github.com/hugo-toha/toha/blob/aa9b49b3180ed6f538659b689001083b9dead242/layouts/partials/sections/home.html#L32) in the [toha](https://github.com/hugo-toha/toha) project to the resolution you want:
```
{{/* apply image processing. don't use "Fit" in svg or gif because its not supported */}}
{{ if and $authorImage (and (ne $authorImage.MediaType.SubType "svg") ( ne $authorImage.MediaType.SubType "gif")) }}
  {{ $authorImage = $authorImage.Fit "148x148" }}
{{ end }}
{{/* get file that matches the filename as specified as src="" in shortcode */}}
{{ $src := resources.Get $backgroundImage }}
```
For background blur, you can delete the [filter settings of the .home.background css class](https://github.com/hugo-toha/toha/blob/aa9b49b3180ed6f538659b689001083b9dead242/assets/styles/sections/home.scss#L16) in asset\styles\sections\home.file.
